version: "3"

services:

    readingisgoodapi:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:80"
        networks:
            - app-network
        depends_on:
            - mongo
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        networks:
            - app-network
        volumes:
            -  mongo-data:/data:db   

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
        networks:
            - app-network
        depends_on:
          - mongo

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local